// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: todos.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTodo = `-- name: CreateTodo :exec
INSERT INTO todos (title, description, user_id) VALUES ($1, $2, $3)
`

type CreateTodoParams struct {
	Title       string
	Description pgtype.Text
	UserID      pgtype.Int8
}

// CREATE
func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) error {
	_, err := q.db.Exec(ctx, createTodo, arg.Title, arg.Description, arg.UserID)
	return err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = $1
`

// DELETE
func (q *Queries) DeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTodo, id)
	return err
}

const deleteTodosByUserId = `-- name: DeleteTodosByUserId :exec
DELETE FROM todos WHERE user_id = $1
`

func (q *Queries) DeleteTodosByUserId(ctx context.Context, userID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteTodosByUserId, userID)
	return err
}

const getTodoById = `-- name: GetTodoById :one
SELECT id, title, description, completed, created_at, updated_at, user_id FROM todos WHERE id = $1
`

// READ
func (q *Queries) GetTodoById(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodoById, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getTodosByUserId = `-- name: GetTodosByUserId :many
SELECT id, title, description, completed, created_at, updated_at, user_id FROM todos WHERE user_id = $1
`

func (q *Queries) GetTodosByUserId(ctx context.Context, userID pgtype.Int8) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getTodosByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :exec
UPDATE todos SET title = $2, description = $3 WHERE id = $1
`

type UpdateTodoParams struct {
	ID          int64
	Title       string
	Description pgtype.Text
}

// UPDATE
func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) error {
	_, err := q.db.Exec(ctx, updateTodo, arg.ID, arg.Title, arg.Description)
	return err
}
